name: swaac.tamouse.org
title: Software as a Craft
author: Tamara Temple
email: tamouse@gmail.com
description: The development blog of tamouse
url: 'https://tamouse.github.io/'
twitter_username: tamouse
github_username: tamouse
social:
  twitter: tamouse
  github: tamouse
defaults:
  author: Tamara Temple


permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


baseurl: ''
source: source
destination: _site

s3path: "https://s3.amazonaws.com/swaac.tamouse.org/"

exclude:
  - '#*'
  - '.#*'
  - '*~'

plugins:
  - jekyll-category-pages
  - jekyll-tag-pages
